#!/bin/bash
set -e;

echo "🚀 Inicializando ecosistema completo de bases de datos..."
echo "📁 Usando arquitectura 100% modular:"
echo "   ├── setup/           - Configuración inicial (usuarios, DBs, permisos)"
echo "   ├── [22 módulos]/    - 22 módulos SQL independientes (incl. Incapacidades IMSS Ene 2026)"
echo "   └── data/            - Datos iniciales y plantillas"

# Definir directorio de scripts SQL
SQL_DIR="/docker-entrypoint-initdb.d/sql"

# =====================================================================
# EJECUTAR SCRIPTS SQL EN ORDEN
# =====================================================================

echo "📄 Ejecutando scripts SQL de inicialización..."

# 1. Crear bases de datos
echo "  1️⃣ Creando bases de datos..."
eval "cat <<EOF
$(cat $SQL_DIR/setup/01-init-databases.sql)
EOF" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"

# 2. Crear usuarios y roles
echo "  2️⃣ Creando usuarios y roles..."
eval "cat <<EOF
$(cat $SQL_DIR/setup/02-create-users.sql)
EOF" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"

# 2. Aplicar esquema SaaS modular
echo "  3️⃣ Aplicando esquema SaaS modular..."
echo ""
echo "    📦 MÓDULO: Core Universal (nueva estructura desacoplada - Nov 2025)"
echo "       🔌 Extensiones PostgreSQL..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/core/fundamentos/01-extensiones.sql"
echo "       🎭 Tipos y enumeraciones (SOLO universales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/core/fundamentos/02-tipos-enums-core.sql"
echo "       ⚡ Funciones utilitarias..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/core/fundamentos/03-funciones-utilidad.sql"
echo "       📋 Tabla dinámica de categorías (reemplaza ENUM industria_tipo)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/core/schema/01-tabla-categorias.sql"
echo ""
echo "    📦 MÓDULO: Templates de Agendamiento (ENUMs y seeds)"
echo "       🎭 ENUMs de dominio (estado_cita, estado_franja)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/templates/01-enums-dominio.sql"
echo "       📋 Categorías de agendamiento (11 industrias)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/templates/seeds/categorias-agendamiento.sql"
echo ""
echo "    🌎 MÓDULO: Ubicaciones Geográficas (Nov 2025)"
echo "       📋 Tablas de ubicaciones (paises, estados, ciudades, codigos_postales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/ubicaciones-geograficas/01-tablas.sql"
echo "       📋 Datos iniciales México (32 estados + ciudades principales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/ubicaciones-geograficas/02-datos-mexico.sql"
echo ""
echo "    📦 MÓDULO: Núcleo (nueva estructura modular)"
echo "       🏛️ Tablas core (organizaciones, usuarios)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/01-tablas-core.sql"
echo "       📊 Índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/03-indices.sql"
echo "       🛡️ Políticas RLS (seguridad multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/04-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (auditoría, timestamps, RBAC)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/05-funciones.sql"
echo "       🔄 Triggers automáticos..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/06-triggers.sql"
echo "       🧩 Funciones del sistema modular (tiene_modulo_activo, validaciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/08-funciones-modulos.sql"
echo "       👁️ Vistas del sistema modular (v_organizaciones_modulos, estadísticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/09-vistas-modulos.sql"
echo "       🔐 Sistema de activación de cuentas (onboarding simplificado)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/10-activaciones-cuenta.sql"
echo ""
echo "    📦 MÓDULO: Catálogos - Tipos de Bloqueo"
echo "       📋 Tablas catálogo (tipos_bloqueo, tipos_profesional)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/tipos-bloqueo/01-tablas.sql"
echo "       📊 Índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/tipos-bloqueo/02-indices.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/tipos-bloqueo/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/tipos-bloqueo/04-funciones.sql"
echo "       🔄 Triggers automáticos..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/tipos-bloqueo/05-triggers.sql"
echo "       📋 Datos iniciales (42 tipos del sistema)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/tipos-bloqueo/06-datos-iniciales.sql"
echo ""
echo "    👷 MÓDULO: Profesionales (Dic 2025 - extraído de negocio)"
echo "       📋 Tabla profesionales..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/01-tablas.sql"
echo "       📊 Índices especializados (11 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/02-indices.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/03-rls-policies.sql"
echo "       🔄 Triggers automáticos..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/04-triggers.sql"
echo "       📨 Sistema de invitaciones..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/servicios/06-invitaciones.sql"
echo ""
echo "    🧑‍💼 MÓDULO: Clientes (Dic 2025 - extraído de negocio)"
echo "       📋 Tabla clientes..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/01-tablas.sql"
echo "       📊 Índices especializados (13 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/02-indices.sql"
echo "       🛡️ Políticas RLS (3 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/03-rls-policies.sql"
echo "       🏷️ Sistema de etiquetas (Ene 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/04-etiquetas.sql"
echo "       📅 Timeline de actividades (Ene 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/05-actividades.sql"
echo "       📄 Documentos y Oportunidades se ejecutan después de Storage (dependencia archivos_storage)..."
echo ""
echo "    🎯 MÓDULO: Servicios"
echo "       📋 Tablas servicios y servicios_profesionales..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/servicios/01-tablas.sql"
echo "       📊 Índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/servicios/02-indices.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/servicios/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/servicios/04-funciones.sql"
echo "       🔄 Triggers automáticos..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/servicios/05-triggers.sql"
echo ""
echo "    🏛️ MÓDULO: Organización (Estructura Organizacional - Dic 2025)"
echo "       📋 Tablas organización (4 tablas: departamentos, puestos, categorias_profesional, profesionales_categorias)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/organizacion/01-tablas.sql"
echo "       📊 Índices especializados (nuevos campos profesionales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/organizacion/02-indices.sql"
echo "       🔗 Foreign Keys diferidas (departamentos, puestos, supervisores)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/organizacion/03-foreign-keys.sql"
echo "       ⚡ Funciones PL/pgSQL (6 funciones: jerarquía, subordinados, validaciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/organizacion/04-funciones.sql"
echo "       🛡️ Políticas RLS (8 políticas multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/organizacion/05-rls-policies.sql"
echo ""
echo "    📅 MÓDULO: Agendamiento (nueva estructura modular)"
echo "       📋 Tablas agendamiento (horarios_profesionales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/01-tablas-agendamiento.sql"
echo "       📊 Índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/02-indices.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/04-funciones.sql"
echo "       🔄 Triggers automáticos..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/05-triggers.sql"
echo "       🔄 Round-Robin (auto-asignación profesionales - Enero 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/agendamiento/06-round-robin.sql"
echo ""
echo "    📅 MÓDULO: Citas (nueva estructura modular)"
echo "       📋 Tablas citas (particionadas) + citas_servicios..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/citas/01-tablas-citas.sql"
echo "       🗓️ Particionamiento mensual..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/citas/02-particionamiento.sql"
echo "       📊 Índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/citas/03-indices.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/citas/04-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/citas/05-funciones.sql"
echo "       🔄 Triggers automáticos..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/citas/06-triggers.sql"
echo ""
echo "    🚫 MÓDULO: Bloqueos (nueva estructura modular)"
echo "       📋 Tabla bloqueos_horarios..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/bloqueos/01-tabla-bloqueos.sql"
echo "       📊 Índices especializados (8 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/bloqueos/02-indices.sql"
echo "       🛡️ Políticas RLS (2 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/bloqueos/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (5 funciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/bloqueos/04-funciones.sql"
echo "       🔄 Triggers automáticos (3 triggers)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/bloqueos/05-triggers.sql"
echo "       👁️ Vistas de consulta (2 vistas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/bloqueos/06-vistas.sql"
echo ""
echo "    📊 MÓDULO: Auditoría (nueva estructura modular)"
echo "       📋 ENUM + Tabla eventos_sistema (particionada)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/01-tablas-eventos.sql"
echo "       📅 Particionamiento mensual (2 particiones iniciales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/02-particionamiento.sql"
echo "       📊 Índices especializados (13 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/03-indices.sql"
echo "       🛡️ Políticas RLS (1 política)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/04-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (5 funciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/05-funciones.sql"
echo "       🔄 Triggers automáticos (2 triggers)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/06-triggers.sql"
echo "       👁️ Vistas de consulta (2 vistas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/auditoria/07-vistas.sql"
echo ""
echo "    📦 MÓDULO: Pagos (nueva estructura modular)"
echo "       💳 Tablas pagos + métodos_pago..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pagos/01-tablas.sql"
echo "       📊 Índices especializados (12 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pagos/02-indices.sql"
echo "       🛡️ Políticas RLS (7 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pagos/03-rls-policies.sql"
echo "       🔄 Triggers automáticos (2 triggers)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pagos/04-triggers.sql"
echo ""
echo "    🤖 MÓDULO: Chatbots (nueva estructura modular)"
echo "       📋 Tablas chatbot_config + chatbot_credentials..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/chatbots/01-tablas.sql"
echo "       📊 Índices especializados (8 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/chatbots/02-indices.sql"
echo "       🛡️ Políticas RLS (4 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/chatbots/03-rls-policies.sql"
echo "       🔄 Triggers automáticos (1 trigger)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/chatbots/04-triggers.sql"
echo ""
echo "    🔧 MÓDULO: Mantenimiento (nueva estructura modular)"
echo "       📋 Tablas configuracion_sistema + eventos_sistema_archivo..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/mantenimiento/01-tablas.sql"
echo "       📊 Índices especializados (2 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/mantenimiento/02-indices.sql"
echo "       🛡️ Políticas RLS (1 política)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/mantenimiento/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (8 funciones: archivado + particiones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/mantenimiento/04-funciones.sql"
echo "       🔄 Triggers automáticos (1 trigger)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/mantenimiento/05-triggers.sql"
echo ""
echo "    🛍️ MÓDULO: Marketplace (nueva estructura modular)"
echo "       📋 Tablas marketplace (4 tablas: perfiles, reseñas, analytics, categorías)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/marketplace/01-tablas-marketplace.sql"
echo "       📊 Índices especializados (24 índices: GIN full-text, geográficos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/marketplace/02-indices.sql"
echo "       🛡️ Políticas RLS (8 políticas: acceso público + tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/marketplace/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (3 funciones: search, stats, perfil completo)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/marketplace/04-funciones.sql"
echo "       🔄 Triggers automáticos (4 triggers)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/marketplace/05-triggers.sql"
echo "       📋 Datos iniciales (10 categorías base)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/marketplace/06-datos-iniciales.sql"
echo ""
echo "    📦 MÓDULO: Inventario (nueva estructura modular)"
echo "       📋 Tablas inventario (4 tablas: categorías, proveedores, productos, movimientos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/01-tablas.sql"
echo "       📊 Índices especializados (20 índices: GIN full-text, stock bajo)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/02-indices.sql"
echo "       🛡️ Políticas RLS (16 políticas: multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (7 funciones: valor, ABC, rotación)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/04-funciones.sql"
echo "       🔄 Triggers automáticos (3 triggers: alertas, timestamps)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/05-triggers.sql"
echo "       📅 Particionamiento mensual de movimientos_inventario..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/06-particionamiento.sql"
echo "       ⏰ Jobs pg_cron (alertas de productos sin movimiento)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/07-jobs-pg-cron.sql"
echo "       📋 Tablas órdenes de compra (3 tablas: órdenes, items, recepciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/08-ordenes-compra-tablas.sql"
echo "       📊 Índices órdenes de compra (12 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/09-ordenes-compra-indices.sql"
echo "       🛡️ Políticas RLS órdenes de compra (6 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/10-ordenes-compra-rls.sql"
echo "       ⚡ Funciones y triggers órdenes de compra (5 funciones + 4 triggers)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/11-ordenes-compra-funciones.sql"
echo ""
echo "    💰 MÓDULO: POS (Punto de Venta)"
echo "       📋 Tablas POS (3 tablas: ventas, items, alertas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/01-tablas.sql"
echo "       📊 Índices especializados (14 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/02-indices.sql"
echo "       🛡️ Políticas RLS (12 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (6 funciones: folio, totales, stock, reportes)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/04-funciones.sql"
echo "       🔄 Triggers automáticos (4 triggers: folio, totales, stock, timestamps)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/05-triggers.sql"
echo ""
echo "    💵 MÓDULO: Comisiones (después de POS para triggers de ventas)"
echo "       📋 Tablas comisiones (3 tablas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/comisiones/01-tablas.sql"
echo "       📊 Índices especializados (10 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/comisiones/02-indices.sql"
echo "       🛡️ Políticas RLS (4 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/comisiones/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (5 funciones incl. calcular_comision_venta)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/comisiones/04-funciones.sql"
echo "       🔄 Triggers automáticos (7 triggers incl. ventas POS)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/comisiones/05-triggers.sql"
echo ""
echo "    📊 MÓDULO: Contabilidad (Dic 2025)"
echo "       📋 Tablas contabilidad (6 tablas: cuentas, periodos, asientos, movimientos, config, saldos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/01-tablas.sql"
echo "       📅 Particionamiento mensual de asientos_contables..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/02-particionamiento.sql"
echo "       📊 Índices especializados (27 índices incl. GIN full-text)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/03-indices.sql"
echo "       🛡️ Políticas RLS (12 políticas multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/04-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (12 funciones: asientos automáticos, balanza, PyG)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/05-funciones.sql"
echo "       🔄 Triggers automáticos (8 triggers: cuadre, saldos, asientos POS/compras)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/06-triggers.sql"
echo "       📋 Catálogo de cuentas SAT México (función crear_catalogo_cuentas_sat)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/contabilidad/07-datos-catalogo-sat.sql"
echo ""
echo "    🔔 MÓDULO: Recordatorios (Nov 2025)"
echo "       📋 Tablas recordatorios (configuracion_recordatorios, historial_recordatorios)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/recordatorios/01-tablas.sql"
echo "       📊 Índices especializados (7 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/recordatorios/02-indices.sql"
echo "       🛡️ Políticas RLS (4 políticas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/recordatorios/03-rls.sql"
echo "       ⏰ Job pg_cron y vistas de debugging..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/recordatorios/04-pg-cron.sql"
echo ""
echo "    📁 MÓDULO: Storage (MinIO - Dic 2025)"
echo "       📋 Tabla archivos_storage con RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/storage/01-tablas-storage.sql"
echo ""
echo "    🧑‍💼 MÓDULO: Clientes - Documentos y Oportunidades (requiere Storage)"
echo "       📄 Documentos de cliente (Ene 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/06-documentos.sql"
echo "       💼 Oportunidades B2B (Ene 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/07-oportunidades.sql"
echo "       📋 Crédito Cliente se ejecuta después de POS (dependencia venta_pagos)..."
echo ""
echo "    👷 MÓDULO: Profesionales - Documentos (requiere Storage)"
echo "       📄 Documentos de empleados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/05-documentos-empleado.sql"
echo "       🏦 Cuentas bancarias de empleados (Fase 1 - Enero 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/06-cuentas-bancarias.sql"
echo "       📚 Currículum (experiencia, educación, habilidades - Fase 4 - Enero 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/07-curriculum.sql"
echo "       📋 Onboarding empleados (plantillas, tareas, progreso - Fase 5 - Enero 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/08-onboarding-empleados.sql"
echo "       📋 Catálogo de motivos de salida (GAP-001 vs Odoo 19)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/09-motivos-salida.sql"
echo "       💰 Categorías de pago (GAP-004 vs Odoo 19)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/10-categorias-pago.sql"
echo ""
echo "    🏖️ MÓDULO: Vacaciones (Sistema de Vacaciones - Fase 3 - Enero 2026)"
echo "       📋 Tablas vacaciones (politicas, saldos, solicitudes)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/vacaciones/01-tablas.sql"
echo "       📊 Niveles por antigüedad (LFT México, Colombia)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/vacaciones/02-niveles.sql"
echo ""
echo "    🏥 MÓDULO: Incapacidades IMSS (Enero 2026)"
echo "       📋 Tabla incapacidades..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/incapacidades/01-tablas.sql"
echo "       📊 Índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/incapacidades/02-indices.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/incapacidades/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/incapacidades/04-funciones.sql"
echo "       🏷️ Tipo de bloqueo 'incapacidad'..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/incapacidades/05-tipo-bloqueo.sql"
echo ""
echo "    🎉 MÓDULO: Eventos Digitales (Invitaciones - Dic 2025)"
echo "       📋 Tablas eventos digitales (6 tablas: eventos, invitados, ubicaciones, regalos, felicitaciones, plantillas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/eventos-digitales/01-tablas.sql"
echo "       🛡️ Políticas RLS (5 políticas multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/eventos-digitales/02-rls-policies.sql"
echo "       📊 Índices especializados (20+ índices: token, slug, RSVP, GIN etiquetas)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/eventos-digitales/03-indices.sql"
echo "       🔄 Triggers y funciones (métricas, estadísticas RSVP, evento público)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/eventos-digitales/04-triggers-metricas.sql"
echo "       📋 Datos iniciales (13 plantillas de diseño por tipo de evento)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/eventos-digitales/05-datos-iniciales.sql"
echo ""
echo "    🌐 MÓDULO: Website (Sitio Web Público - Dic 2025)"
echo "       📋 Tablas website (3 tablas: config, paginas, bloques)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/website/01-tablas.sql"
echo "       📊 Índices especializados (8 índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/website/02-indices.sql"
echo "       🛡️ Políticas RLS (9 políticas: público + tenant + superadmin)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/website/03-rls-policies.sql"
echo ""
echo "    🎛️ MÓDULO: Custom Fields (Campos Personalizados - Dic 2025)"
echo "       📋 Tablas custom_fields (2 tablas: definiciones, valores)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/custom-fields/01-tablas.sql"
echo "       📊 Índices especializados (12 índices: GIN full-text, covering)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/custom-fields/02-indices.sql"
echo "       🛡️ Políticas RLS (2 políticas multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/custom-fields/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (3 funciones: obtener, guardar, validar)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/custom-fields/04-funciones.sql"
echo "       🔄 Triggers automáticos (4 triggers: timestamps, sync, limpieza)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/custom-fields/05-triggers.sql"
echo ""
echo "    🔔 MÓDULO: Notificaciones (Centro de Notificaciones - Dic 2025)"
echo "       📋 Tablas notificaciones (4 tablas: notificaciones, preferencias, plantillas, tipos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/notificaciones/01-tablas.sql"
echo "       📊 Índices especializados (10 índices: feed, contador, expiración)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/notificaciones/02-indices.sql"
echo "       🛡️ Políticas RLS (3 políticas: por usuario y organizacion)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/notificaciones/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (9 funciones: crear, leer, archivar, feed, preferencias)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/notificaciones/04-funciones.sql"
echo "       🔄 Triggers automáticos (4 triggers: citas, stock, reseñas + pg_cron)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/notificaciones/05-triggers.sql"
echo ""
echo "    ✅ MÓDULO: Workflows de Aprobación (Dic 2025)"
echo "       📋 Tablas workflows (6 tablas: definiciones, pasos, transiciones, instancias, historial, delegaciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/workflows/01-tablas.sql"
echo "       📊 Índices especializados (15 índices: bandeja aprobaciones, historial)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/workflows/02-indices.sql"
echo "       ⚡ Funciones PL/pgSQL (6 funciones: puede_aprobar, obtener_delegado, evaluar_condicion)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/workflows/03-funciones.sql"
echo "       📋 Datos iniciales (tipos notificación + workflow default OC + permisos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/workflows/04-datos-iniciales.sql"
echo ""
echo "    🏢 MÓDULO: Sucursales (Multi-ubicación - Dic 2025)"
echo "       📋 Tablas sucursales (7 tablas: sucursales, usuarios, profesionales, servicios, stock, transferencias)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/sucursales/01-tablas.sql"
echo "       📊 Índices especializados (20+ índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/sucursales/02-indices.sql"
echo "       🛡️ Políticas RLS (28 políticas multi-tenant)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/sucursales/03-rls-policies.sql"
echo "       ⚡ Funciones PL/pgSQL (8 funciones: códigos, stock, transferencias)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/sucursales/04-funciones.sql"
echo "       🔄 Triggers automáticos (8 triggers: auto-matriz, asignaciones, workflow transferencias)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/sucursales/05-triggers.sql"
echo "       🔗 Foreign Keys a tablas existentes (18 FK + índices)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/sucursales/06-foreign-keys.sql"
echo ""
echo "    📍 MÓDULO: Ubicaciones de Trabajo (GAP-003 vs Odoo 19)"
echo "       📋 Tabla ubicaciones_trabajo (trabajo híbrido)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/catalogos/ubicaciones-trabajo/01-tablas.sql"
echo "       🔗 FKs diferidas profesionales→GAPs (motivos, categorías, ubicaciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/profesionales/11-foreign-keys-gaps.sql"
echo ""
echo "    🎨 MÓDULO: Variantes de Producto (Dic 2025) - ANTES de reservas"
echo "       📋 Tablas atributos, valores, variantes + RLS + datos iniciales..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/20-variantes-producto.sql"
echo ""
echo "    🔒 MÓDULO: Reservas de Stock (Fase 1 Gaps Inventario - Dic 2025)"
echo "       📋 Tabla reservas_stock + funciones + RLS + pg_cron job..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/12-reservas-stock.sql"
echo ""
echo "    📍 MÓDULO: Ubicaciones WMS (Fase 3 Gaps Inventario - Dic 2025)"
echo "       📋 Tablas ubicaciones_almacen + stock_ubicaciones + funciones..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/13-ubicaciones-almacen.sql"
echo ""
echo "    📊 MÓDULO: Valoración Inventario (Fase 3 Gaps Inventario - Dic 2025)"
echo "       📋 Tablas valoracion_inventario + funciones FIFO/AVCO..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/14-valoracion-inventario.sql"
echo ""
echo "    🔢 MÓDULO: Números de Serie/Lotes (Fase 3 Gaps Inventario - Dic 2025)"
echo "       📋 Tablas numeros_serie + historial + funciones trazabilidad..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/15-numeros-serie.sql"
echo ""
echo "    📈 MÓDULO: Stock Proyectado (Fase 4 Gaps Inventario - Dic 2025)"
echo "       📋 Funciones stock proyectado + alertas inteligentes..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/16-stock-proyectado.sql"
echo ""
echo "    🛤️ MÓDULO: Rutas de Operación (Fase 5 Gaps Inventario - Dic 2025)"
echo "       📋 Tablas rutas, productos_rutas, reglas, transferencias + funciones..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/17-rutas-operacion.sql"
echo ""
echo "    📅 MÓDULO: Inventory at Date (Snapshots Históricos - Dic 2025)"
echo "       📋 Tablas snapshots + funciones consulta histórica + pg_cron..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/21-inventory-at-date.sql"
echo ""
echo "    📋 MÓDULO: Conteo Físico (Sprint 1 Inventario Avanzado - Dic 2025)"
echo "       📋 Tablas conteos + conteos_items + funciones + triggers..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/22-conteo-fisico.sql"
echo ""
echo "    📊 MÓDULO: Ajustes Masivos CSV (Sprint 2 Inventario Avanzado - Dic 2025)"
echo "       📋 Tablas ajustes_masivos + items + funciones procesamiento..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/23-ajustes-masivos.sql"
echo ""
echo "    🔄 MÓDULO: Reorden Automático (Sprint 3 Inventario Avanzado - Dic 2025)"
echo "       📋 Tabla reorden_logs + funciones evaluación + job pg_cron 6:00 AM..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/24-reorden-automatico.sql"
echo "       💰 Landed Costs (costos adicionales en OC)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/25-landed-costs.sql"
echo "       🚚 Dropshipping (OC directa proveedor→cliente)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/26-dropshipping.sql"
echo "       🛤️ Rutas Multietapa (Pick→Pack→Ship, Recepción→QC→Stock)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/27-rutas-multietapa.sql"
echo "       📦 Batch/Wave Picking (consolidación de pedidos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/28-batch-picking.sql"
echo "       📦 Paquetes de Envío (bultos para empaque)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/29-paquetes-envio.sql"
echo "       🤝 Consigna (inventario en consignación)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/30-consigna.sql"
echo "       🔢 Consigna + Números de Serie (NS en consigna)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/31-consigna-numeros-serie.sql"
echo "       💰 Consigna + Venta POS (trigger automático)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/inventario/32-consigna-venta-pos.sql"
echo ""
echo "    🔗 MÓDULO: POS FKs Diferidos (después de inventario avanzado)"
echo "       📋 FKs a numeros_serie y variantes_producto..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/06-foreign-keys.sql"
echo ""
echo "    💰 MÓDULO: POS Fase 2 (Ene 2026)"
echo "       🏦 Sesiones de Caja (apertura/cierre, movimientos)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/07-sesiones-caja.sql"
echo "       💳 Pagos Split (múltiples métodos de pago por venta)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/08-venta-pagos.sql"
echo "       🎟️ Cupones de Descuento (códigos promocionales)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/09-cupones.sql"
echo "       🎁 Promociones Automáticas (motor reglas JSON)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/10-promociones.sql"
echo "       ⭐ Programa de Lealtad (puntos, niveles, canje)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/11-programa-lealtad.sql"
echo "       📦 Combos y Modificadores (paquetes, extras, personalizaciones)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/pos/12-combos-modificadores.sql"
echo ""
echo "    💳 MÓDULO: Crédito Cliente (requiere venta_pagos)"
echo "       💰 Sistema de Crédito / Fiado (Ene 2026)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/clientes/08-credito-cliente.sql"
echo ""
echo "    🔐 MÓDULO: Permisos Normalizados (Sistema de Permisos - Dic 2025)"
echo "       📋 Tablas permisos (3 tablas: catalogo, rol, usuario_sucursal)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/11-tablas-permisos.sql"
echo "       ⚡ Funciones PL/pgSQL (5 funciones: obtener_permiso, tiene_permiso, verificar_permiso_middleware)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/12-funciones-permisos.sql"
echo "       📋 Datos iniciales (65+ permisos en 10 módulos + asignaciones por rol)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/13-datos-permisos.sql"
echo ""
echo "    💰 MÓDULO: Multi-Moneda (Dic 2025)"
echo "       📋 Tablas monedas (4 tablas: monedas, tasas_cambio, precios_servicio_moneda, precios_producto_moneda)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/15-tablas-monedas.sql"
echo ""
echo "    🎭 MÓDULO: Roles Dinámicos (Ene 2026)"
echo "       📋 Tabla roles (roles por organización, trigger auto-crear en nuevas orgs)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/16-tabla-roles.sql"
echo "       ⚡ Funciones permisos V2 (obtener_permiso_v2, tiene_permiso con rol_id)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/nucleo/17-funciones-permisos-v2.sql"
echo ""
echo "    🏷️ MÓDULO: Listas de Precios (Dic 2025 - Fase 5)"
echo "       📋 Tablas listas_precios y listas_precios_items..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/precios/01-tablas.sql"
echo "       ⚡ Funciones (obtener_precio_producto, obtener_precios_carrito)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/precios/02-funciones.sql"
echo "       🛡️ Políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/precios/03-rls-policies.sql"
echo "       🔗 Alter tabla clientes (lista_precios_id)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/precios/04-alter-clientes.sql"
echo "       🔐 Permisos del catálogo..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/precios/05-datos-permisos.sql"
echo "       📋 Datos iniciales (lista default por organización)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/precios/06-datos-iniciales.sql"
echo ""
echo "    💳 MÓDULO: Suscripciones-Negocio (Enero 2026)"
echo "       📋 Tablas suscripciones-negocio (5 tablas: planes, suscripciones, pagos, cupones, webhooks)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/suscripciones-negocio/01-tablas.sql"
echo "       ⚡ Funciones métricas SaaS (MRR, ARR, Churn, LTV, crecimiento)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/suscripciones-negocio/02-funciones-metricas.sql"
echo "       📋 Datos iniciales Nexo Team (4 planes: trial, basico, pro, enterprise)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/suscripciones-negocio/03-datos-nexo-team.sql"
echo "       🔐 Permisos del módulo suscripciones-negocio..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/suscripciones-negocio/04-datos-permisos.sql"
echo "       🔌 Conectores de pago multi-tenant (Stripe, MercadoPago)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/suscripciones-negocio/05-conectores-pago.sql"
echo "       🎟️ Tokens de checkout (Customer Billing)..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/suscripciones-negocio/06-checkout-tokens.sql"
echo ""
echo "✅ Migración completa a arquitectura modular finalizada (23 módulos independientes)"
echo ""

# 3. Insertar plantillas de servicios - ELIMINADO (sistema de plantillas removido)
# echo "  4️⃣ Insertando plantillas de servicios por industria..."
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/data/plantillas-servicios.sql"

# 4. Configurar permisos específicos del SaaS (después de crear tablas)
echo "  5️⃣ Configurando permisos finales en tablas..."
eval "cat <<EOF
$(cat $SQL_DIR/setup/03-grant-permissions.sql)
EOF" | psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB"

# 5. Crear super administrador inicial (DESHABILITADO - Ahora se hace via interfaz web)
# echo "  6️⃣ Creando super administrador inicial..."
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$SQL_DIR/setup/04-create-superadmin.sql" || echo "⚠️  Super admin no creado (puede crearse después via API)"
echo "  6️⃣ Super admin se creará via interfaz web en el primer acceso"

# =====================================================================
# VALIDACIÓN POST-INSTALACIÓN
# =====================================================================

echo "🔍 Validando instalación..."

# Verificar que las bases de datos fueron creadas
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    SELECT
        datname as "Base de Datos",
        pg_size_pretty(pg_database_size(datname)) as "Tamaño"
    FROM pg_database
    WHERE datname IN ('${POSTGRES_DB}', 'n8n_db', 'chat_memories_db')
    ORDER BY datname;
EOSQL

# Verificar que los usuarios fueron creados
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
    SELECT
        rolname as "Usuario",
        rolcanlogin as "Puede Login",
        rolsuper as "Superusuario"
    FROM pg_roles
    WHERE rolname IN ('saas_app', 'n8n_app', 'readonly_user', 'integration_user')
    ORDER BY rolname;
EOSQL

# Verificar que las tablas principales fueron creadas en la base SaaS
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT
        schemaname as "Esquema",
        tablename as "Tabla",
        pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) as "Tamaño"
    FROM pg_tables
    WHERE schemaname = 'public'
    AND tablename IN ('usuarios', 'organizaciones', 'profesionales', 'clientes', 'servicios', 'citas', 'horarios_disponibilidad', 'horarios_profesionales', 'suscripciones_org', 'planes_suscripcion_org', 'eventos_sistema', 'bloqueos_horarios', 'pagos', 'metodos_pago', 'website_config', 'departamentos', 'puestos', 'categorias_profesional')
    ORDER BY tablename;
EOSQL

# Verificar índices especializados creados
echo "📊 Verificando índices especializados..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT
        COUNT(*) as "Total Índices",
        COUNT(*) FILTER (WHERE indexname LIKE 'idx_%') as "Índices Especializados"
    FROM pg_indexes
    WHERE schemaname = 'public';
EOSQL

# Verificar políticas RLS habilitadas
echo "🛡️ Verificando políticas RLS..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT
        tablename as "Tabla",
        COUNT(*) as "Políticas RLS"
    FROM pg_policies
    WHERE schemaname = 'public'
    GROUP BY tablename
    ORDER BY tablename;
EOSQL

# Verificar cantidad de plantillas de servicios insertadas - ELIMINADO (sistema de plantillas removido)
# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
#     SELECT
#         tipo_industria,
#         COUNT(*) as "Servicios Template"
#     FROM plantillas_servicios
#     GROUP BY tipo_industria
#     ORDER BY tipo_industria;
# EOSQL

echo ""
echo "✅ Configuración de bases de datos completada exitosamente:"
echo ""
echo "📊 BASES DE DATOS CREADAS:"
echo "  ├── ${POSTGRES_DB} (SaaS principal)"
echo "  ├── n8n_db (workflows n8n)"
echo "  └── chat_memories_db (AI Agent histories)"
echo ""
echo "👤 USUARIOS CREADOS:"
echo "  ├── saas_app (aplicación SaaS principal)"
echo "  ├── n8n_app (n8n workflows)"
echo "  ├── readonly_user (solo lectura - analytics)"
echo "  └── integration_user (integraciones cross-DB)"
echo ""
echo "🗄️ ESQUEMA SAAS MODULAR:"
echo "  ├── 🎭 8 ENUMs especializados (tipos de negocio + bloqueos)"
echo "  ├── ⚡ 64 funciones PL/pgSQL automáticas (incl. inventario, POS, archivado y particionamiento)"
echo "  ├── 🏛️ 25 tablas enterprise (core + negocio + operaciones + inventario + POS + auditoría)"
echo "  ├── ⚡ Tablas PARTICIONADAS: citas, eventos_sistema y movimientos_inventario (range partitioning mensual)"
echo "  ├── 📊 300+ índices optimizados (covering + GIN compuestos + full-text + parciales)"
echo "  ├── 🛡️ 56+ políticas RLS multi-tenant 100% documentadas"
echo "  ├── 🔄 29+ triggers automáticos de validación (incl. stock y alertas inventario)"
echo "  ├── 💳 Módulo Suscripciones-Negocio (MRR, ARR, Churn, webhooks Stripe/MercadoPago)"
echo "  ├── 💰 Integración Mercado Pago (pagos + métodos de pago + idempotencia)"
echo "  ├── 📦 Sistema de Inventario (productos, stock, proveedores, órdenes de compra, análisis ABC)"
echo "  ├── 🛒 Punto de Venta (ventas, tickets, reportes de caja)"
echo "  ├── 🧹 Sistema de archivado automático (eventos + citas)"
echo "  ├── ⏰ pg_cron configurado: 5 jobs automáticos (particiones inventario, archivado, vacuum)"
echo "  └── 🔧 Mejoras post-auditoría aplicadas: FKs CASCADE + covering indexes + partitioning"
echo ""
echo "🔐 SEGURIDAD:"
echo "  ├── Cada aplicación tiene su propio usuario"
echo "  ├── Permisos mínimos necesarios por servicio"
echo "  ├── Usuario de solo lectura para reportes"
echo "  ├── RLS configurado para multi-tenancy"
echo "  └── Usuario de integración con permisos específicos"
echo ""
echo "⚙️ CONFIGURACIÓN:"
echo "  └── Tabla 'db_connections_config' creada con configuraciones de conexión"
echo ""
echo "📁 ESTRUCTURA MODULAR:"
echo "  ├── Arquitectura 100% modular con 23 módulos SQL independientes"
echo "  ├── Migración completa (17 Nov 2025): directorio schema/ legacy eliminado"
echo "  ├── Nuevo módulo Marketplace (17 Nov 2025): Directorio público SEO-optimizado"
echo "  ├── Nuevos módulos Inventario + POS (20 Nov 2025): Fase 0 completada"
echo "  ├── Nuevo módulo Ubicaciones (24 Nov 2025): Catálogo geográfico México"
echo "  ├── Nuevo módulo Website (6 Dic 2025): Sitio web público por organización"
echo "  ├── Nuevo módulo Organización (18 Dic 2025): Estructura organizacional (departamentos, puestos, categorías)"
echo "  ├── Nuevo módulo Permisos (21 Dic 2025): Sistema normalizado de permisos (catalogo, roles, overrides)"
echo "  ├── Nuevo módulo Workflows (22 Dic 2025): Motor de aprobaciones para OC (6 tablas, bandeja, delegaciones)"
echo "  ├── Nuevo módulo Incapacidades (8 Ene 2026): IMSS, prórrogas, integración bloqueos"
echo "  ├── Nuevo módulo Roles Dinámicos (21 Ene 2026): Roles personalizados por organización"
echo "  ├── Nuevo módulo Suscripciones-Negocio (21 Ene 2026): SaaS interno (5 tablas, MRR, ARR, Churn, webhooks Stripe/MP)"
echo "  ├── Máxima mantenibilidad (100-500 líneas por archivo)"
echo "  ├── Mejoras post-auditoría aplicadas (Oct 2025): Calificación 9.5/10"
echo "  ├── Documentación completa en sql/README.md"
echo "  └── Escalable para 1000+ organizaciones y 10M+ citas/mes"
echo ""
echo "🎯 PRÓXIMOS PASOS:"
echo "  ├── El backend Node.js puede conectarse con las credenciales configuradas"
echo "  ├── Módulo suscripciones-negocio listo (crear planes desde backend/frontend)"
echo "  ├── Cron jobs de suscripciones se inicializan automáticamente (6AM y 7AM)"
echo "  ├── Webhooks Stripe/MercadoPago listos (validación HMAC obligatoria)"
echo "  ├── Los modelos de datos pueden ser probados"
echo "  ├── Integración Mercado Pago lista en BD (falta backend + webhooks)"
echo "  └── Consulta sql/schema/README.md para detalles de la arquitectura"