-- ====================================================================
-- ⚠️  ARCHIVO MIGRADO A ESTRUCTURA MODULAR
-- ====================================================================
--
-- Este archivo ha sido migrado a:
-- → sql/00-fundamentos/02-tipos-enums.sql
--
-- Fecha de migración: 16 Noviembre 2025
-- Fase de refactoring: FASE 1 - Fundamentos
--
-- NO AGREGAR CONTENIDO AQUÍ
-- Este archivo será eliminado al finalizar el refactoring
-- ====================================================================
