-- Script para limpiar datos de test
-- Ejecutar como admin antes de correr los tests

BEGIN;

-- Desactivar temporalmente RLS
ALTER TABLE citas DISABLE ROW LEVEL SECURITY;
ALTER TABLE clientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE profesionales DISABLE ROW LEVEL SECURITY;
ALTER TABLE servicios DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE organizaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE servicios_profesionales DISABLE ROW LEVEL SECURITY;
ALTER TABLE horarios_disponibilidad DISABLE ROW LEVEL SECURITY;
ALTER TABLE horarios_profesionales DISABLE ROW LEVEL SECURITY;
ALTER TABLE bloqueos_horarios DISABLE ROW LEVEL SECURITY;

-- Truncar tablas
TRUNCATE TABLE citas RESTART IDENTITY CASCADE;
TRUNCATE TABLE servicios_profesionales RESTART IDENTITY CASCADE;
TRUNCATE TABLE horarios_disponibilidad RESTART IDENTITY CASCADE;
TRUNCATE TABLE horarios_profesionales RESTART IDENTITY CASCADE;
TRUNCATE TABLE bloqueos_horarios RESTART IDENTITY CASCADE;
TRUNCATE TABLE servicios RESTART IDENTITY CASCADE;
TRUNCATE TABLE profesionales RESTART IDENTITY CASCADE;
TRUNCATE TABLE clientes RESTART IDENTITY CASCADE;
TRUNCATE TABLE usuarios RESTART IDENTITY CASCADE;
TRUNCATE TABLE organizaciones RESTART IDENTITY CASCADE;

-- Reactivar RLS
ALTER TABLE citas ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE profesionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicios ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE organizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicios_profesionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE horarios_disponibilidad ENABLE ROW LEVEL SECURITY;
ALTER TABLE horarios_profesionales ENABLE ROW LEVEL SECURITY;
ALTER TABLE bloqueos_horarios ENABLE ROW LEVEL SECURITY;

COMMIT;
