-- ====================================================================
-- MÓDULO NÚCLEO: DATOS INICIALES
-- ====================================================================
-- Datos de configuración inicial del sistema:
-- • Planes de subscripción (trial, pro, custom)
--
-- Modelo de Negocio (Dic 2025):
-- • Trial: 14 días de prueba con acceso completo
-- • Pro: Todas las apps, $249 MXN/usuario/mes
-- • Custom: Plan personalizado (precio negociado)
--
-- Migrado de: sql/schema/10-subscriptions-table.sql
-- Fecha migración: 16 Noviembre 2025
-- Actualización: 3 Diciembre 2025 - Modelo Trial/Pro (sin Free)
-- ====================================================================
-- NOTA: SUPER_ADMIN SIN ORGANIZACIÓN (Nov 2025)
-- ====================================================================
-- El super_admin es un usuario de plataforma que NO pertenece a ninguna
-- organización. Gestiona todas las organizaciones desde /superadmin/*.
-- Las organizaciones se crean cuando usuarios normales se registran.
-- ====================================================================
